name: Reusable WF

on:
  push:

  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        # branch to test
        description: 'branch to test'
        # Default value if no value is explicitly provided
        default: 'master'
        required: false

# job
jobs:
  call-push-job:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      buildtype: Release
      testargs: -D LONG_TESTS=YES
      event_name: ${{ github.event_name }}
      branch_name:  ${{github.event.inputs.branch}}

#  call-workflow-dispatch-job:
#    if: github.event_name == 'workflow_dispatch'
#    uses: ./.github/workflows/reusable-workflow.yml
#    with:
#      buildtype: Debug
#      testargs: -D LONG_TESTS=YES
#      event_name: ${{ github.event_name }}
#      branch_name:  ${{github.event.inputs.branch}}