name: GitHub macOS and Ubuntu CI

on: [push, pull_request]

jobs:
    steps:
      - uses: actions/checkout@v2

      - name: Install VTK
          macOS:
            runs-on: macOS-10.15
            run: |
              brew install vtk@8.2
              brew link vtk@8.2
            # cp /usr/local/opt/hdf5/lib/libhdf5.dylib /usr/local/opt/hdf5/lib/libhdf5.200.dylib
            # cp /usr/local/opt/hdf5/lib/libhdf5_hl.dylib /usr/local/opt/hdf5/lib/libhdf5_hl.200.dylib
            # cp /usr/local/opt/hdf5/lib/libhdf5_hl_cpp.dylib /usr/local/opt/hdf5/lib/libhdf5_hl_cpp.200.dylib
          linux:
            runs-on: ubuntu-latest
            run:
              sudo apt-get install vtk
              
      - name: Install Sctoch
        run: |
          git clone https://gitlab.inria.fr/scotch/scotch.git && cd scotch
          git checkout v6.1.3
          cd src && cp Make.inc/Makefile.inc.i686_mac_darwin10 Makefile.inc
          make scotch -j "$NJOBS"
          make install scotch -j "$NJOBS"
        env:
          NJOBS: "2"

      - name: Install LibCommons
        run: |
          git clone https://github.com/ISCDtoolbox/Commons.git && cd Commons
          mkdir build
          cd build && cmake ..
          make install
          
      - name: Install LinearElasticity
        run: |
          git clone https://github.com/ISCDtoolbox/LinearElasticity.git && cd LinearElasticity
          mkdir build
          cd build && cmake ..
          make install

      - name: Build Mmg
        run: |
          git clone https://github.com/MmgTools/mmg.git && cd mmg
          mkdir build && cd build
          cmake -DBUILD_TESTING=ON ..
          make -j "$NJOBS" mmg2d
          ctest -R mmg2d_vtkvtk_ani -VV
        env:
          NJOBS: "2"
