name: GitHub windows CI

# on: [push, pull_request]
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Branch to test'
        # Default value if no value is explicitly provided
        default: 'main'
        # Input has to be provided for the workflow to run
        required: false

jobs:
  windows:
    runs-on: windows-2022
  
    steps:
      - uses: actions/checkout@v2

      - name: Configure Mmg      
        run: |
          git clone https://github.com/MmgTools/mmg.git
          cd mmg
          mkdir build
          cd build
          cmake -DCI_CONTEXTE=ON  -DBUILD_TESTING=ON  ..
        shell: powershell
        
      - name: Build Mmg      
        run: |
          cd mmg/build
          cmake  --build . --config Release
        shell: powershell
          
      - name: Test Mmg
        run: |
          cd mmg/build
          ctest -C Release -R msh -VV
        shell: powershell
