name: GitHub CI

on:
  push:
    branches: [main]

  workflow_dispatch:


jobs:
  ci:
    runs-on: self-hosted

    steps:
      # checkout the provided branch name if workflow is manually run
      - uses: actions/checkout@v3

      - name: Check the host runner architecture
        run: |
          uname -a

      #- name: Fix ssh Could not resolve hostname
      #  run: |
      #    ssh-keyscan ${{ secrets.PPC64LE_MACHINE_IP }}  >> ~/.ssh/known_hosts # Add live server IP to known hosts.  

      - name: ssh into the ppc64le machine and execute the script
        run: |
          echo -e "SSH into the Power machine and execute the script\n"
          ssh ${{ secrets.BOUNCE_USERNAME }}@${{ secrets.BOUNCE_MACHINE_IP }} < arch
          ssh ${{ secrets.BOUNCE_USERNAME }}@${{ secrets.BOUNCE_MACHINE_IP }} < echo "coucou" < arch
          ssh ${{ secrets.BOUNCE_USERNAME }}@${{ secrets.BOUNCE_MACHINE_IP }} <  ssh ${{ secrets.PPC64LE_USERNAME }}@${{ secrets.PPC64LE_MACHINE_IP }} < arch
