name: GitHub CI

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        # branch to test
        description: 'branch to test'
        # Default value if no value is explicitly provided
        default: 'main'
        required: false

env:
  if: matrix.os == 'windows-2022'
  TOTO: "windows"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    # Launch a matrix of jobs
    strategy:
        matrix:
          os: [ubuntu-20.04,windows-2022,macos-10.15]
          pattern: [on,off]
          #scotch: [on,off]


    steps:
      # checkout the provided branch name if workflow is manually run
      - uses: actions/checkout@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{github.event.inputs.branch}}

      # checkout the event branch for automatic workflows
      - uses: actions/checkout@v2
        if: github.event_name != 'workflow_dispatch'

      - name: RunnerWin PatternOff
        if: matrix.pattern == 'off' && matrix.os == 'windows-2022'
        run: |
          echo " RunnerWin $RUNNER_OS PatternOff: $TOTO"

      - name: RunnerUbuntu
        run: |
          echo " Runner $RUNNER_OS: $TOTO"
