on:
  workflow_call:
    inputs:
      buildtype:
        description: 'CMAKE build type'
        type: string
        default: Release
        required: true

      testargs:
        description: additionals ctest arguments
        required: false
        type: string

      branch_name:
        description: branch to checkout for manual triggering
        required: false
        type: string

      event_name:
        description: github event name
        required: true
        type: string

# job
jobs:
  ci:
    runs-on: ${{ matrix.os }}

    # Launch a matrix of jobs
    strategy:
        matrix:
            os: [ubuntu-20.04]
            pattern: [on,off]
            scotch: [on,off]

    steps:
      - name: Print options and set environment variables
        run: |
          echo "${{ github.event.inputs.name }}:
            Os:      ${{ matrix.os }},
            Pattern: ${{ matrix.pattern }},
            Scotch:  ${{ matrix.scotch }}"

      - name: Print param values
        run: |
          echo  ${{ inputs.testargs }}  ${{ inputs.buildtype }} ${{ inputs.event_name }} ${{ inputs.branch_name }}
          echo " PARAMNAME: $INPUT_PARAMNAME"

      - uses: actions/checkout@v2
        if: inputs.event_name != 'workflow_dispatch'

      - uses: actions/checkout@v2
        if: inputs.event_name == 'workflow_dispatch'
        with:
          ref: ${{ inputs.branch_name }}

      - name: is testable
        if inputs.branch_name != ''
          run: echo "ok"

      - name: is testable
        if inputs.branch_name
          run: echo "ok2"