on:
  workflow_call:
    inputs:
      buildtype:
        description: 'CMAKE build type'
        type: string
        default: Release
        required: true

      testargs:
        description: additionals ctest arguments
        required: false
        type: string

      branchname:
        description: branch name
        required: false
        type: string

# job
jobs:
  ci:
    runs-on: ${{ matrix.os }}

    # Launch a matrix of jobs
    strategy:
        matrix:
            os: [ubuntu-20.04]
            pattern: [on,off]
            scotch: [on,off]

    steps:
      - name: Print options and set environment variables
        run: |
          echo "${{ github.event.inputs.name }}:
            Os:      ${{ matrix.os }},
            Pattern: ${{ matrix.pattern }},
            Scotch:  ${{ matrix.scotch }}"

      - name: Test Args val
        run: |
          echo  ${{ inputs.testargs }}  ${{ inputs.buildtype }}
          echo "$INPUT_PARAMNAME ${{ inputs.branchname }}"
          ctest -VV ${{ env.TEST_FLG }} ${{ inputs.testargs }}
