name: GitHub multi arch CI

on:
  # run tests on push events
  push:
  # run tests on PR events
  pull_request:
  # run tests manually on a given branch (default is master)
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        # branch to test
        description: 'branch to test'
        # Default value if no value is explicitly provided
        default: 'master'
        required: false

# job
jobs:
  Mmg tests:
    runs-on: [macOS-10.15,ubuntu-20.04]

    # Launch a matrix of jobs
    strategy:
        matrix:
            build: [Release]
            pattern: [on,off]
            scotch: [on,off]
            vtk: [off]
            include:
              # test vtk only without scotch and with delaunay insertion (more
              # tests are useless)
              - build: Release
                pattern: off
                scotch: off
                vtk: on

    steps:
      # checkout the provided branch name if workflow is manually run
      - uses: actions/checkout@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{github.event.inputs.branch}}

      # checkout the event branch for automatic workflows
      - uses: actions/checkout@v2
        if: github.event_name != 'workflow_dispatch'

      - name: message
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            echo "linux"
          elif [ "$RUNNER_OS" == "MacOS" ]; then
            echo "osx"
          else
            echo "???"
          fi
