name: workflow_call

on:
  # run tests on push events
  push:

  # run tests manually on a given branch (default is master)
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        # branch to test
        description: 'branch to test'
        # Default value if no value is explicitly provided
        default: 'main'
        required: false

# job
jobs:
  build_gen:
    uses: ./.github/workflows/main-job.yml
    with:
      branch_name:  ${{github.event.inputs.branch}}
      OS: ${{ matrix.os }}
      BUILD_GENERATOR: ${{ matrix.BUILD_GENERATOR }}

    name: BUILD-gen-arg-${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04,macos-12]
        include:
          - os: ubuntu-22.04
            BUILD_GENERATOR: "--makefile"

          - os: ubuntu-24.04


  no_build_gen:
    uses: ./.github/workflows/main-job.yml
    with:
      branch_name:  ${{github.event.inputs.branch}}
      OS: ${{ matrix.os }}

    name: no-BUILD-gen-arg-${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04,macos-12]
        include:
          - os: ubuntu-22.04
